version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      - echo "Current directory is..."
      - pwd
      - echo "Listing all files to debug..."
      - ls -R
      - echo "Preparing Lambda deployment packages..."
      - zip -j lf1.zip "./lambda-functions/LF1 Photo Index.py"
      - zip -j lf2.zip "./lambda-functions/LF2 Photo Search.py"
  post_build:
    commands:
      - echo "Updating Lambda functions..."
      - aws lambda update-function-code --function-name index-photos --zip-file fileb://lf1.zip
      - aws lambda update-function-code --function-name lambda-search --zip-file fileb://lf2.zip
artifacts:
  files:
    - '**/*'
  base-directory: 'front-end/apiGateway-js-sdk'
